version: "3.3"
services:
  liberty:
    build: .
    ports:
      - "9080:9080"
    depends_on:
      - db2_inventory
      - db2_order
    environment:
      DB2_HOST_ORDER: db2_order
      DB2_HOST_INVENTORY: db2_inventory
      BOOTSTRAP: "yes"
  db2_inventory:
    image: store/ibmcorp/db2_developer_c:11.1.2.2b-x86_64
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: INDB
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
  db2_order:
    image: store/ibmcorp/db2_developer_c:11.1.2.2b-x86_64
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: ORDERDB
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "false"
      REPODB: "false"
